[base]
package = puffer_phc
env_name = puffer_phc
vec = native
policy_name = CleanRLPolicy
# rnn_name = Recurrent

[env]
motion_file = "sample_data/amass_train_take6_upright.pkl"

[robot]
has_self_collision = True

[train]
seed = 1
torch_deterministic = True
device = cuda

cpu_offload = False
compile = False
norm_adv = True
target_kl = None

total_timesteps = 1_000_000
eval_timesteps = 30_000
num_envs = 32
# num_workers = 2
# env_batch_size = 1
# batch_size = 131072
batch_size = 8192
# minibatch_size = 32768
minibatch_size = 1024
update_epochs = 1
bptt_horizon = 16
anneal_lr = False
gae_lambda = 0.9776227170639571
gamma = 0.8567482546637853
clip_coef = 0.011102333784435113
clip_vloss = True
vf_coef = 0.3403069830175013
vf_clip_coef = 0.26475190539131727
max_grad_norm = 0.8660179376602173
ent_coef = 0.01376980586465873
learning_rate = 0.002064722899262613
checkpoint_interval = 1000
