[base]
package = puffer_phc
env_name = puffer_phc
vec = native
policy_name = CleanRLPolicy
# rnn_name = Recurrent

[env]
motion_file = "sample_data/dfaust_one_leg_jump.pkl"

[robot]
has_self_collision = True

[train]
seed = 1
torch_deterministic = True
device = cuda

cpu_offload = False
compile = False
norm_adv = True
target_kl = None

total_timesteps = 1_000_000_000
eval_timesteps = 100_000

num_envs = 2048
batch_size = 65536
minibatch_size = 16384

; num_envs = 32
; batch_size = 1024
; minibatch_size = 256

update_epochs = 6
bptt_horizon = 8
anneal_lr = False
gae_lambda = 0.99
gamma = 0.95
clip_coef = 0.2
clip_vloss = True
vf_coef = 2.0
vf_clip_coef = 0.2
max_grad_norm = 0.5
ent_coef = 0.0
learning_rate = 0.0002

checkpoint_interval = 100000
